version: '3'
services:
  order-service:
    build:
      context: ./order-service
    ports:
      - '3000:3000'
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  payment-service:
    build:
      context: ./payment-service
    ports:
      - '3001:3001'
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
